### ISSUE TITLE
Item damage/maintenance

### ISSUE THREAD

**Issue by jgthibodeau** [umts/aggressive-epsilon#16]
In #12 you noted that items can be made unreservable (eg for maintenance), but how does this work if the item is returned and in need of repair, but it has been reserved for a time before it will be fixed?

**Comment by dfaulken** [comment]
Currently this app just stores state. Anyone who can change the reservability of an item also has read access to the reservations for that item.

**Comment by tomecho** [comment]
probable-engine has been updated to set available to false on items.
